const pizzaToppings=["sausage", "bacon", "ham", "pineapple"]
const greetCustomer ="Howdie!"
for(let i = pizzaToppings.length - 1; >= i++)
console.log(${greetcustomer}`Welcome to Big Papas pizza`, `Where we offer ${pizzaToppings} and more.`)


const getPizzaOrder = "big papa"
let size =12`inch`
let crust ="stuffed"
pizzaToppings=[3]
console.log(`your ${getPizzaOrder}, ${size}, ${crust} ,with ${pizzaToppings} is coming up !`)




 const preparePizza = `Big Papa Pizza`
 toppings: `sausage, ham ,spinach,green peppers, hot honey`
 crust: `stuffed`
 size: 16
 cooking: true;
greeting : `we are cooking pizza`

console.log(preparePizza.greeting);
 console.log(preparePizza);
 console.log(preparePizza.toppings);
console.log(preparePizza.crust);
console.log(preparePizza.size);
console.log(preparePizza.cooking)

const servePizza = `country style !`
size : `Large`
crust: `thin`
topping:[`ham , pineapple , green onion`]
serve: true


servePizza: `country style`
console.log(`Order up here is your ${preparePizza}, ${size} ,with  ${toppings} Enjoy !`)
return(${preparePizza} serve: `delivered`) ;
