const pizzaToppings=["sausage", "bacon", "ham", "pineapple"]
let greeting ="Howdie! Welcome to Big Papa's Pizza. We offer"
for(let i =0; pizzaToppings.length; i++) {
  greeting += `${pizzaToppings [i]}`;
console.log(${greeting}`Welcome to Big Papas pizza`, `Where we offer ${pizzaToppings} and more.`)


getPizzaOrder = 12 , ("thick crust" , "infinite toppings");{
let size =12`inch`
let crust ="stuffed"
pizzaToppings = "infinite toppings"
console.log(`your ${getPizzaOrder}, ${size}, ${crust} ,with ${pizzaToppings} is coming up !`)




 function preparePizza ([orderSize, orderCrust, ordercrazyToppings]) {
  console.log("Cooking pizza !") }


  return {
size: orderSize
crust: orderCrust
toppings: crazyToppings


servePizza(pizza) ;
let orderReady = `order up ! Heres your ${pizza.size} ${pizza.crust} crust pizza ` ;

for(let toppings of toppings) {
  orderReady += `${toppings}`
console.log(`${orderReady. Enjoy}`)
return pizza
